# Generated by Django 5.2.6 on 2025-09-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_studentregistration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='class_name',
        ),
    ]
