# Generated by Django 5.2.6 on 2025-09-04 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
        ('myapp', '0006_remove_studentregistration_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='cources.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
